spring:
  datasource:
    username: root
    password: 730707
    # Mac电脑需要配置：useSSL=false
    # MySQL8中时区配置：serverTimezone=UTC
    # 编码格式配置：useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/mpstudy?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    # MySQL5.x 驱动：com.mysql.jdbc.Driver
    # MySQL8 驱动：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#  #服务名
#  application:
#    name: liujia

# 配置日志
# 我们所有的sql现在是控制台可见的
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case=false: true
#配置logic删除
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  #指定的Mapper.xml文件
#  mapper-locations: classpath*:mybatis/*.xml

#logging:
#  config: classpath:log4j2.xml
